### ISSUE TITLE
Please become Certified Kubernetes

### ISSUE THREAD

**Issue by dankohn** [cybozu-go/cke#132]
You need to become Certified Kubernetes to use the name Cybozu Kubernetes Engine.

Please see https://github.com/cncf/k8s-conformance/ or email conformance@cncf.io with questions.

Cc @caniszczyk @taylorwaggoner

**Comment by ymmt2005** [comment]
@dankohn 
Thank you for letting us know that our product name is violating CNCF terms and conditions.
We will be considering to apply the certification program.

In the meantime, we are going to take immediate actions to remove the word "Kubernetes"
from our documents and websites, calling this product just "cke".

**Comment by dankohn** [comment]
Thank you.

**Comment by ymmt2005** [comment]
@dankohn 
Just wanted to let you know that we have joined CNCF and submitted the conformance test result of CKE!
https://github.com/cncf/k8s-conformance/pull/702

**Comment by ymmt2005** [comment]
CKE 1.15.1 is now a certified Kubernetes installer.
https://github.com/cncf/k8s-conformance/tree/master/v1.15/cke
