### ISSUE TITLE
[KAIZEN] CI workflow fails randomly

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/cke#169]
## What

Sometimes CI workflow fails randomly. Which jobs fail are different one by one.

## How

TBD

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
These days, we have not seen unstable tests.

**Comment by ymmt2005** [comment]
Closing because we do not see unstable tests for long.
