### ISSUE TITLE
Make sonobuoy great again

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/cke#281]
## What

The current sonobuoy job takes too long (> 3 hours).
Life is short, so make it faster!

## How

- Use non-nested VMs.

## Checklist

- [x] Finish implentation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by tapih** [comment]
check versions in `sonbuoy/Makefile`
