### ISSUE TITLE
Failed to update squid deployment with SSA

### ISSUE THREAD

**Issue by tapih** [cybozu-go/cke#311]
**Describe the bug**

After applying [this release](https://github.com/cybozu-go/neco/releases/tag/release-2020.04.08-8660) to the staging environment, CKE failed to apply the squid deployment.

This resource is applied with SSA and the failure is caused by the SSA conflict.
The corresponding CKE operation is `resource-apply` and the error message is `Apply failed with 1 conflict: conflict with \"before-first-apply\" using apps/v1: .spec.template.spec.containers[name=\"squid\"].image`.

**Environments**
- Version: v1.17.1

**To Reproduce**
1. Run CKE v1.17.0
2. Update CKE to v1.17.1

**Expected behavior**
`squid` is deployed with no error.

**Additional context**

**Comment by dulltz** [comment]
CKE should always use force apply.

https://v1-17.docs.kubernetes.io/docs/reference/using-api/api-concepts/#using-server-side-apply-in-a-controller

**Comment by tapih** [comment]
The issue to the upstream:
https://github.com/kubernetes/kubernetes/issues/89954
