### ISSUE TITLE
Question regarding metallb + ipvs

### ISSUE THREAD

**Issue by malozanoff** [cybozu-go/cke#351]
Hello,

Sorry to barge in, i usually check what you guys are doing as you have an extremely similar infrastructure as we do.
We ran into an issue with metallb + contour (well, mostly metallb related) and i'm wondering if you faced this before and how you solved it.

There seems to be an issue with kube-proxy blackholing load balancer external ips (creating entries for the metallb ip with no endpoints) when using externalTrafficPolicy: Local, this causes traffic inside the cluster to not be able to route, it works fine when coming from outside as the anycast will land on a node with an actual pod so there will be a route.

This is the metallb ticket: https://github.com/metallb/metallb/issues/153
This is (one of) the kubernetes tickets: https://github.com/kubernetes/kubernetes/issues/75262

Just curious if you found this issue in your infrastructure and how you solved it.

Thanks!

**Comment by ymmt2005** [comment]
Hi @malozanoff !

The problem can be worked around by adding `--ipvs-strict-arp=true` to kube-scheduler.
https://github.com/metallb/metallb/issues/153#issuecomment-518651132

For CKE, we have the following cluster configuration file:
https://github.com/cybozu-go/neco/blob/master/etc/cke-template.yml#L28-L29
