### ISSUE TITLE
K8s 1.22: use policy/v1 for Eviction

### ISSUE THREAD

**Issue by morimoto-cybozu** [cybozu-go/cke#497]
## What

The API version for policy resources, e.g. PodDisruptionBudget, was upgraded from policy/v1beta1 to policy/v1 at K8s 1.21.
The "pod/eviction" subresource, however, accepts "policy/v1" eviction requests only from K8s 1.22.
Update `op/reboot.go` to use policy/v1 package.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by umezawatakeshi** [comment]
This modification is being done in https://github.com/cybozu-go/cke/pull/540
