### ISSUE TITLE
Add metrics to indicate whether the resources managed by CKE are synced

### ISSUE THREAD

**Issue by zeroalphat** [cybozu-go/cke#694]
## What

When manually editing a CKE-managed resource, CKE may not be able to delete fields in the resource.

1. Edit some fields of a resource managed by CKE using the kubectl command. For example, edit `spec.template.spec.containers[0].resources.limits`.
2. Delete the same fields (resources.limits) from the file from which the CKE-managed resources are defined that you manually changed.Raise the revision number so that CKE will update the resource.
3. Update CKE and make the release.
4. CKE applies the resource with Server-side apply (SSA) because the revision of the resource has been updated. However, even if CKE applies the resource with SSA, it cannot delete the field because the field to be deleted is managed by another manager.
Even if the CKE cannot delete the field, no error or other problem occurs, so the field remains as it is.

## How

- Add metrics to indicate whether the resources managed by CKE are synced.

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by takara9** [comment]
必要になったら、Openして実施
